image_root: C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3/data/test/DCM
root_path: C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3
CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.5

model_paths:
  512: []
  1024: 
    - C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3/ensemble/(#65)hrnet_w64_epoch_125_dice_0.9715.pt
    # - C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3/ensemble/DeeplabV3_1024_lr2e4_adamW_78.pt
  1536: 
    -  C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3/ensemble/hrnet_w18_epoch_24_dice_0.9730.pt
  2048: []

save_dir: C:/Users/lucky/study/level2-cv-semanticsegmentation-cv-01-lv3/ensemble
output_name: soft_ensemble_2m_1127_noCLAHE.csv